joomla:
  image: joomla
  links:
    - joomladb:mysql
  ports:
    - 8080:80
  volumes:
    - $PWD/www:/var/www/html

joomladb:
  image: mysql:5.6
  container_name: joomladb
  volumes:
    - $PWD/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
